# ==========================================
# 1. K\u1ebft n\u1ed1i SQL Server
# ==========================================
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=diabetes_care_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ==========================================
# 2. C\u1ea5u h\u00ecnh Hibernate
# ==========================================
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# ==========================================
# 3. C\u1ea5u h\u00ecnh Email (S\u1eed d\u1ee5ng th\u00f4ng tin gi\u1ea3 \u0111\u1ec3 app kh\u1edfi \u0111\u1ed9ng \u0111\u01b0\u1ee3c)
# ==========================================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nothing@gmail.com
spring.mail.password=nothing
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ==========================================
# 4. C\u1ea5u h\u00ecnh Thymeleaf (H\u1ed7 tr\u1ee3 view HTML)
# ==========================================
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false

server.port=8082