spring.datasource.password=123456
spring.mail.username=Minhduy22032006@gmail.com
spring.mail.password=dqtv ezbz vvxx xxds
spring.security.oauth2.client.registration.google.client-id=825557210321-g1h9c41g0c5k126r75qog1fgvfu2pvm9.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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